project:
  type: website

website:
  title: "MADS"
  description: "MADS - Multi-Agent Distributed System"
  site-url: "https://mads-net.github.io"
  draft-mode: unlinked
  navbar:
    left:
      - href: guides.qmd
        text: "Guides"
      - text: "Presentations"
        menu:
          - href: presentations/intro.qmd
            text: "MADS Intro"
    right:
      - about.qmd

format:
  html:
    toc: true
    email-obfuscation: "javascript"
    theme: 
      - flatly
      - brand
      - custom.scss
